path: /data/kb081434/repos/10k_teacher/train/ # root dir(absolute path)
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path') 

# Classes
names:
  0: card
  1: cardholder
  2: earbuds
  3: glasses
  4: gloves
  5: muffler
  6: phone
  7: umbrella
  8: wallet(deprecated)
